### ISSUE TITLE
.net Binding (remaining checklist)

### ISSUE THREAD

**Issue by jumpinjackie** [jumpinjackie/mapguide-api-bindings#28]
- [x] Verify nuget package is consumable on full .net framework without any additional changes
   - [x] Add MSBuild targets file for full framework to ensure unmanaged dlls are being copied to output
   - [x] Have `MapGuideDotNetApi` build for `AnyCPU`
- [x] Add full framework version of entire .net test suite
- [x] Ensure it builds (Linux)
- [x] Make .net test suite pass (Linux)
   - [x] String parameters seem to be completed discarded or trashed (eg. `new MgUserInformation("username", "password")` throws `MgInvalidArgumentException` due to empty string parameters)

**Comment by jumpinjackie** [comment]
The only remaining test failures on Linux are already known test failures. Closing.
